export default {
    avt: require('./source/image.png'),
    anh1: require('./source/anh1.png'),
    anh2: require('./source/anh2.png'),
    anh3: require('./source/anh3.png'),
    anh4: require('./source/anh4.png'),
    anh5: require('./source/anh5.png'),
    anh6: require('./source/anh6.png'),
    buttonStart: require('./source/button-start.png'),
    topic: require('./source/chuDe.png'),
    dreamy: require('./source/dream.png'),
    fashion: require('./source/fashion.png'),
    art: require('./source/art.png'),
    dark: require('./source/dark.png'),
    nickname: require('./source/nickname.png'),
    button: require('./source/bg-button.png'),
    backgroundImg: require('./source/backgroundImg.jpg'),
    IconNickname: require('./source/IconNickname.png'),
    IconTP: require('./source/IconTP.png'),
    Screen1: require('./source/screen1.png'),
    TextScreen1: require('./source/TextScreen1.png'),
    TextScreen2: require('./source/TextScreen2.png'),
    TextScreen3: require('./source/TextScreen3.png'),
    TextScreen4: require('./source/TextScreen4.png'),
    suggest: require('./source/SuggestName.png'),
    screentest: require('./source/screentest.png'),
    
};