let PathRoute = {
    Home: '/',
    Contact: '/contact-us',
    HolidayCamp: '/holiday-camps',
    OneTraining: '/1-on-1-training',
    BirthdayParty: '/birthday-parties',
    WeeklyTraining: '/weekly-football-training',
    WeeklyTrainingWithAlias: (alias) => `/${alias}/weekly-football-training`,
    // Franchise: '/franchise/:alias-:id([0-9]+)',
    Franchise: '/:title',
    AboutUs: '/about-us',
    Location: '/location',
    ListQNA: '/faqs',
    DetailQNA: '/faqs/:cateAlias',
    HomeNews: '/news',
    ListNews: '/news/:cateAlias',
    DetailNews: '/news/:alias-:id([0-9]+)',
    BookTrialTraining: '/book-trial-training',
    BookTrialTrainingWithAlias: (alias) => `/${alias}/book-trial-training`,
    BookTrialCamp: '/book-trial-camp',
    ThankYou: '/thank-you',
    AcademyNews: '/:alias/news',
    Policy: '/policies',
    PolicyWithParam: '/policies/:title',
    SchoolTraining: '/school-training',
    Error: '/error',
    JoinUs: '/join-us',
    Coaching: '/join-us/coaching',
    ParentHost: '/join-us/parent-host',
};

export default PathRoute;
