export const loginActionType = {
    LOGIN_SUBMIT: 'LOGIN_SUBMIT',
    LOGIN_SUCCESS: 'LOGIN_SUCCESS',
    LOGIN_FAILED: 'LOGIN_FAILED',
};

export const headerActionType = {
    CHANGE_LOCATION: 'CHANGE_LOCATION',
    CLOSE_LOCATION: 'CLOSE_LOCATION',
    CLOSE_MAP_POPUP: 'CLOSE_MAP_POPUP',
};

export const homeActionType = {
    GET_HOME: 'GET_HOME',
    GET_HOME_SUCCESS: 'GET_HOME_SUCCESS',
    GET_HOME_FAILED: 'GET_HOME_FAILED',

    GET_ABOUT: 'GET_ABOUT',
    GET_ABOUT_SUCCESS: 'GET_ABOUT_SUCCESS',
    GET_ABOUT_FAILED: 'GET_ABOUT_FAILED',
};
export const userActionType = {};
export const siteActionType = {
    GET_LIST_SITE: 'GET_LIST_SITE',
    GET_LIST_SITE_SUCCESS: 'GET_LIST_SITE_SUCCESS',
    GET_LIST_SITE_FAILED: 'GET_LIST_SITE_FAILED',

    GET_SITE_HAS_CAMP: 'GET_SITE_HAS_CAMP',
    GET_SITE_HAS_CAMP_SUCCESS: 'GET_SITE_HAS_CAMP_SUCCESS',
    GET_SITE_HAS_CAMP_FAILED: 'GET_SITE_HAS_CAMP_FAILED',

    GET_DETAIL_SITE: 'GET_DETAIL_SITE',
    GET_DETAIL_SITE_SUCCESS: 'GET_DETAIL_SITE_SUCCESS',
    GET_DETAIL_SITE_FAILED: 'GET_DETAIL_SITE_FAILED',

    BOOK_TRAINING: 'BOOK_TRAINING',
    BOOK_TRAINING_SUCCESS: 'BOOK_TRAINING_SUCCESS',
    BOOK_TRAINING_FAILED: 'BOOK_TRAINING_FAILED',

    SEARCH_NEARBY: 'SEARCH_NEARBY',
    SEARCH_NEARBY_SUCCESS: 'SEARCH_NEARBY_SUCCESS',
    SEARCH_NEARBY_FAILED: 'SEARCH_NEARBY_FAILED',

    FIND_NEARBY: 'FIND_NEARBY',
    FIND_NEARBY_SUCESS: 'FIND_NEARBY_SUCESS',
    FIND_NEARBY_FAILED: 'FIND_NEARBY_FAILED',

    PICK_DEFAULT_ACADEMY: 'PICK_DEFAULT_ACADEMY',
    SELECTED_MARKER: 'SELECTED_MARKER',
    KEY_CODE: 'KEY_CODE',

    GET_LIST_COURSE: 'GET_LIST_COURSE',
    GET_LIST_COURSE_SUCCESS: 'GET_LIST_COURSE_SUCCESS',
    GET_LIST_COURSE_FAILED: 'GET_LIST_COURSE_FAILED',

    COURSE_START_DATE: 'COURSE_START_DATE',
    COURSE_START_DATE_SUCCESS: 'COURSE_START_DATE_SUCCESS',
    COURSE_START_DATE_FAILED: 'COURSE_START_DATE_FAILED',

    BOOK_COURSE: 'BOOK_COURSE',
    BOOK_COURSE_SUCCESS: 'BOOK_COURSE_SUCCESS',
    BOOK_COURSE_FAILED: 'BOOK_COURSE_FAILED',

    BOOK_COURSE_SIGNUP: 'BOOK_COURSE_SIGNUP',
    BOOK_COURSE_SIGNUP_SUCCESS: 'BOOK_COURSE_SIGNUP_SUCCESS',
    BOOK_COURSE_SIGNUP_FAILED: 'BOOK_COURSE_SIGNUP_FAILED',

    BOOK_EVENT_SIGNUP: 'BOOK_EVENT_SIGNUP',
    BOOK_EVENT_SIGNUP_SUCCESS: 'BOOK_EVENT_SIGNUP_SUCCESS',
    BOOK_EVENT_SIGNUP_FAILED: 'BOOK_EVENT_SIGNUP_FAILED',

    ADD_WAITING: 'ADD_WAITING',
    ADD_WAITING_SUCCESS: 'ADD_WAITING_SUCCESS',
    ADD_WAITING_FAILED: 'ADD_WAITING_FAILED',

    GET_BOOKING: 'GET_BOOKING',
    GET_BOOKING_SUCCESS: 'GET_BOOKING_SUCCESS',
    GET_BOOKING_FAILED: 'GET_BOOKING_FAILED',

    EVENT_DATE: 'EVENT_DATE',
    EVENT_DATE_SUCCESS: 'EVENT_DATE_SUCCESS',
    EVENT_DATE_FAILED: 'EVENT_DATE_FAILED',

    FIND_NEARBY_ACADEMY: 'FIND_NEARBY_ACADEMY',
    FIND_NEARBY_ACADEMY_SUCCESS: 'FIND_NEARBY_ACADEMY_SUCCESS',
    FIND_NEARBY_ACADEMY_FAILED: 'FIND_NEARBY_ACADEMY_FAILED',

    SEND_EMAIL: 'SEND_EMAIL',
    SEND_EMAIL_SUCCESS: 'SEND_EMAIL_SUCCESS',
    SEND_EMAIL_FAILED: 'SEND_EMAIL_FAILED',

    GET_FOOTER_CONFIG: 'GET_FOOTER_CONFIG',
    GET_FOOTER_CONFIG_SUCCESS: 'GET_FOOTER_CONFIG_SUCCESS',
    GET_FOOTER_CONFIG_FAILED: 'GET_FOOTER_CONFIG_FAILED',

    REFRESH_DEFAULT_DATA: 'REFRESH_DEFAULT_DATA',
    REFRESH_DEFAULT_DATA_SUCCESS: 'REFRESH_DEFAULT_DATA_SUCCESS',
    REFRESH_DEFAULT_DATA_FAILED: 'REFRESH_DEFAULT_DATA_FAILED',

    GET_POLICY: 'GET_POLICY',
    GET_POLICY_SUCCESS: 'GET_POLICY_SUCCESS',
    GET_POLICY_FAILED: 'GET_POLICY_FAILED',
};
export const articleActionType = {
    GET_LIST_NEWS: 'GET_LIST_NEWS',
    GET_LIST_NEWS_SUCCESS: 'GET_LIST_NEWS_SUCCESS',
    GET_LIST_NEWS_FAILED: 'GET_LIST_NEWS_FAILED',

    GET_LIST_FAQ: 'GET_LIST_FAQ',
    GET_LIST_FAQ_SUCCESS: 'GET_LIST_FAQ_SUCCESS',
    GET_LIST_FAQ_FAILED: 'GET_LIST_FAQ_FAILED',

    DETAIL_ARTICLE: 'DETAIL_ARTICLE',
    DETAIL_ARTICLE_SUCCESS: 'DETAIL_ARTICLE_SUCCESS',
    DETAIL_ARTICLE_FAILED: 'DETAIL_ARTICLE_FAILED',
};
